version: '3'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 5001
    networks:
      - backend
      
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - 5002
    depends_on:
      - product
    networks:
      - backend

networks:
  backend: